/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller.vistas;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import taller.modelo.Aparatos;
import taller.modelo.AparatosData;
import taller.modelo.ClienteData;
import taller.modelo.Clientes;
import taller.modelo.Conexion;

/**
 *
 * @author Usuario
 */
public class VistaAparatos extends javax.swing.JInternalFrame {
    
    private AparatosData aparatosData;
    private Conexion conexion;
    private ClienteData cd;
    private ArrayList<Clientes> listaClientes;
    private Clientes cliente;
    /**
     * Creates new form VistaAparatos
     */
    public VistaAparatos() {
        try {
            initComponents();
            conexion = new Conexion();
            cd = new ClienteData(conexion);
                                   
            listaClientes = (ArrayList)cd.obtenerClientes();
            for(Clientes cl: listaClientes){
                jcbDueños.addItem(cl);
            }
            aparatosData = new AparatosData(conexion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAparatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        javax.swing.JLabel jLaparatos = new javax.swing.JLabel();
        jLnumero = new javax.swing.JLabel();
        jLdueño = new javax.swing.JLabel();
        jLfechi = new javax.swing.JLabel();
        jLfeche = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jtSerie = new javax.swing.JTextField();
        jtFechaI = new javax.swing.JTextField();
        jtFechaE = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jLtipo = new javax.swing.JLabel();
        jtTipo = new javax.swing.JTextField();
        jcbDueños = new javax.swing.JComboBox<>();

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLaparatos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLaparatos.setText("APARATOS");

        jLnumero.setText("N deSerie");

        jLdueño.setText("Dueño");

        jLfechi.setText("Fecha Ingreso");

        jLfeche.setText("Fecha Egreso");

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSerieActionPerformed(evt);
            }
        });

        jtFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFechaIActionPerformed(evt);
            }
        });

        jtFechaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFechaEActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jBactualizar.setText("Actualizar");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jLtipo.setText("Tipo Aparato");
        jLtipo.setToolTipText("");

        jtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBborrar)
                        .addGap(29, 29, 29)
                        .addComponent(jBactualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLaparatos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLnumero)
                                    .addComponent(jLdueño)))
                            .addComponent(jLfeche)
                            .addComponent(jLfechi)
                            .addComponent(jLtipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jtFechaE, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jtFechaI, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jcbDueños, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBlimpiar)
                    .addComponent(jBbuscar))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLaparatos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnumero)
                    .addComponent(jBbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdueño)
                    .addComponent(jcbDueños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtipo)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLfechi)
                    .addComponent(jtFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLfeche, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtFechaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBborrar)
                    .addComponent(jBactualizar)
                    .addComponent(jBlimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFechaIActionPerformed

    private void jtFechaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFechaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFechaEActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
              int nroDeSerie = Integer.parseInt(jtSerie.getText());
              
              Aparatos aparato = aparatosData.buscarAparatos(nroDeSerie);
              
              if(aparato != null){
              jcbDueños.setSelectedItem(aparato.getDueño().getIdCliente());
              jtTipo.setText(aparato.getTipoAparato());             
              jtFechaI.setText(aparato.getFechaIngreso().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
              jtFechaE.setText(aparato.getFechaEgreso().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        } else {
                System.out.println("El aparato no se encuentra en la base de datos");
                jOptionPane1.showMessageDialog(null, "El aparato no se encuentra en la base de datos", "ERROR", jOptionPane1.ERROR_MESSAGE);  
              }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSerieActionPerformed

    private void jtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTipoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Clientes dueño = (Clientes)jcbDueños.getSelectedItem();
        String tipo = jtTipo.getText();
        LocalDate fechaI = LocalDate.parse(jtFechaI.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate fechaE = LocalDate.parse(jtFechaE.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        Aparatos aparato = new Aparatos (dueño, tipo, fechaI, fechaE);
        aparatosData.guardarAparato(aparato);
        jtSerie.setText(aparato.getNroDeSerie()+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        
         if(jtSerie.getText() != null){
         int nroDeSerie = Integer.parseInt(jtSerie.getText());
         aparatosData.borrarAparatos(nroDeSerie);
        } else {
            System.out.println("El numero de serie seleccionado no se encuentra en la base de datos");
            jOptionPane1.showMessageDialog(null, "El numero de serie seleccionado no se encuentra en la base de datos", "ERROR", jOptionPane1.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBborrarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
            if(jtSerie.getText() != null){
            
            int nroDeSerie = Integer.parseInt(jtSerie.getText());
            Clientes dueño = (Clientes)jcbDueños.getSelectedItem();
            String tipo = jtTipo.getText();
            LocalDate fechaI = LocalDate.parse(jtFechaI.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate fechaE = LocalDate.parse(jtFechaE.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            Aparatos aparato = new Aparatos(nroDeSerie, dueño, tipo, fechaI, fechaE);
            aparatosData.actualizarAparatos(aparato);
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBactualizarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
       jtSerie.setText("");   
       jcbDueños.setSelectedItem("");
       jtTipo.setText("");
       jtFechaI.setText("");
       jtFechaE.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JLabel jLdueño;
    private javax.swing.JLabel jLfeche;
    private javax.swing.JLabel jLfechi;
    private javax.swing.JLabel jLnumero;
    private javax.swing.JLabel jLtipo;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JComboBox<Clientes> jcbDueños;
    private javax.swing.JTextField jtFechaE;
    private javax.swing.JTextField jtFechaI;
    private javax.swing.JTextField jtSerie;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables
}
